fly-deploy:
  image: golang:1.16
  before_script:
    - apt-get update -qq && apt-get install -y curl
    - curl -L https://fly.io/install.sh | sh
  script:
    - flyctl deploy
  extends:
    - .jgit_filter
  environment:
    name: fly.dev
