fly-deploy:
  stage: deploy
  image: golang:1.16
  before_script:
    - apt-get update -qq && apt-get install -y curl
    - curl -L https://fly.io/install.sh | sh
  script:
    - /root/.fly/bin/flyctl deploy
  extends:
    - .jgit_filter
    - .docker_europe_tags
  environment:
    name: fly.dev
  needs: []
