.jgit_filter:
  only:
    refs:
      - jgit

.jgit_stage_instance:
  environment:
    name: stage
  extends:
    - .deploy_instance
    - .jgit_filter

stage instance:
  extends:
    - .jgit_stage_instance
    - .docker_europe_tags

prod instance:
  extends:
    - .prod_instance
    - .docker_europe_tags
  variables:
    CONSUL_PATH: configs/ks-1/checker/config

stage instance ks1:
  extends:
    - .stage_instance
    - .docker_europe_tags
  variables:
    CONSUL_PATH: configs/ks-1/checker/testconfig
