variables:
  GOOS: "linux"
  GOARCH: "amd64"
  CGO_ENABLED: 0
  GO_VERSION: "latest"

.cache_modules:
  cache:
    policy: pull
    paths:
      - /go/pkg/mod

update modules:
  image: golang:${GO_VERSION}
  stage: cache
  script:
    - go get -v -d ./...
  only:
    changes:
      - go.mod
  extends:
    - .cache_modules
  cache:
    policy: push