variables:
  #CI_DEBUG_TRACE: "true"
  DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
  INST_API_URL: "http://inst-api.service.${INSTANCE_DC}.consul"
  INST_UI_URL: "http://inst-ui.service.${INSTANCE_DC}.consul"
  GO_VERSION: "1.14"
  INJECT_VERSION: "true"
  PACKER_ONLY: "centos"
  BINARY_NAME: "checker"
  INSTANCE_DC: ks-1
  VERSION: ${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
  REGISTRY_TAG: ${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
  CONSUL_PATH: ""

include:
  - project: "ci-library/ci-collections"
    file: "go-app.base.yml"
  - .gitlab-ci.build.yml

prod instance:
  extends:
    - .prod_instance
    - .docker_europe_tags
  variables:
    DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
    INSTANCE_DC: ks-1
    CONSUL_PATH: configs/ks-1/checker/config

stage instance:
  extends:
    - .stage_instance
    - .docker_europe_tags
  variables:
    DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
    INSTANCE_DC: ks-1
    CONSUL_PATH: configs/ks-1/checker/testconfig

wl-staging instance:
  extends:
    - .prod_instance
    - .docker_europe_tags
  variables:
    DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
    INST_API_URL: "https://inst-api.service.${INSTANCE_DC}.consul"
    INST_UI_URL: "https://inst-ui.service.${INSTANCE_DC}.consul"
    INSTANCE_DC: wl-staging
    CONSUL_PATH: configs/checker
