stages:
  - test
  - build
  - package
  - deploy
  - version

include:
  - local: .gitlab-ci.common.yml
  - local: .gitlab-ci.go-common.yml
  - local: .gitlab-ci.go-test.yml
  - local: .gitlab-ci.go-build.yml
  - local: .gitlab-ci.go-docker.yml
  - project: "ci-library/common"
    file: ".gitlab-ci.version.yml"