.jgit_filter:
  only:
    refs:
      - jgit

.jgit_stage_instance:
  environment:
    name: stage
  extends:
    - .deploy_instance
    - .jgit_filter

stage instance:
  extends:
    - .jgit_stage_instance
    - .docker_europe_tags

prod instance:
  extends:
    - .prod_instance
    - .docker_europe_tags
  variables:
    DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
    INSTANCE_DC: ks-1
    CONSUL_PATH: configs/ks-1/checker/config
    REGISTRY_TAG: ${CI_COMMIT_REF_NAME}

stage instance ks1:
  extends:
    - .stage_instance
    - .docker_europe_tags
  variables:
    DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
    INSTANCE_DC: ks-1
    CONSUL_PATH: configs/ks-1/checker/testconfig
