variables:
  #CI_DEBUG_TRACE: "true"
  DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
  INST_API_URL: "http://inst-api.service.${INSTANCE_DC}.consul"
  INST_UI_URL: "http://inst-ui.service.${INSTANCE_DC}.consul"
  GO_VERSION: "1.14"
  INJECT_VERSION: "true"
  PACKER_ONLY: "centos"
  BINARY_NAME: "checker"
  INSTANCE_DC: ks-1
  VERSION: ${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
  REGISTRY_TAG: ${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}

include:
  - project: "ci-library/ci-collections"
    file: "go-app.base.yml"

.build_inject_cmd: &build_inject_cmd |
  go build -v -i -x -ldflags \
  "-X config.Version=${CI_COMMIT_REF_NAME} -X config.VersionSHA=${CI_COMMIT_SHORT_SHA} -X config.VersionBuild=${CI_JOB_ID}" \
  -o build/${BINARY_NAME}

dev instance:
  script:
    - /bin/true
