stages:
  - test
  - build
  - deploy
  - version
  - destroy

variables:
  DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
  INST_API_URL: "http://inst-api.service.${INSTANCE_DC}.consul"
  INST_UI_URL: "http://inst-ui.service.${INSTANCE_DC}.consul"
  BINARY_NAME: "checker"
  INSTANCE_DC: ks-1

include:
  - project: "ci-library/common-ci"
    file: common.yml
  - project: "ci-library/version"
    file: manual.yml
  - project: "ci-library/inst-deploy"
    file: common.yml

  - .gitlab-ci/*.yml
  - .gitlab-ci/werf/*.yml

  - project: 'ci-library/werf-deploy'
    file: 'common.yml'
