variables:
  GOOS: "linux"
  GOARCH: "amd64"
  CGO_ENABLED: 0
  GO_VERSION: "latest"

.go_image:
  image: golang:${GO_VERSION}

.cache_modules:
  cache:
    policy: pull
    paths:
      - /go/pkg/mod
      - /go/bin/golint

update modules:
  stage: cache
  script:
    - go get -v -d ./...
    - go get -u golang.org/x/lint/golint
  only:
    changes:
      - go.mod
      - go.sum
  extends:
    - .go_image
    - .cache_modules
  cache:
    policy: push