variables:
  #CI_DEBUG_TRACE: "true"
  DEPLOY_REPO_URL: "git::ssh://git@jgit.me/instantiator/tests/guide-deploy//go-app"
  GO_VERSION: "1.12.2"
  INJECT_VERSION: "true"
  PACKER_ONLY: "alpine"

include:
  - project: "ci-library/ci-collections"
    file: "go-app.base.yml"

