
prod instance:
  extends:
    - .prod_instance
    - .docker_europe_tags
  variables:
    DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
    INSTANCE_DC: ks-1
    CONSUL_PATH: configs/ks-1/checker/config

stage instance:
  extends:
    - .stage_instance
    - .docker_europe_tags
  variables:
    DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
    INSTANCE_DC: ks-1
    CONSUL_PATH: configs/ks-1/checker/testconfig

wl-staging:
  extends:
    - .stage_instance
    - .docker_europe_tags
  variables:
    DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
    INST_API_URL: "https://inst-api.service.${INSTANCE_DC}.consul"
    INST_UI_URL: "https://inst-ui.service.${INSTANCE_DC}.consul"
    INSTANCE_DC: wl-staging
    CONSUL_PATH: configs/checker

iron-staging:
  extends:
    - .stage_instance
    - .docker_europe_tags
  variables:
    DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
    INST_API_URL: "http://inst-api.service.${INSTANCE_DC}.consul"
    INST_UI_URL: "http://inst-ui.service.${INSTANCE_DC}.consul"
    INSTANCE_DC: iron-staging
    CONSUL_PATH: configs/checker

siam-staging:
  extends:
    - .stage_instance
    - .docker_europe_tags
  variables:
    DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
    INST_API_URL: "http://inst-api.service.${INSTANCE_DC}.consul"
    INST_UI_URL: "http://inst-ui.service.${INSTANCE_DC}.consul"
    INSTANCE_DC: siam-staging
    CONSUL_PATH: configs/checker

mgcat-staging:
  extends:
    - .stage_instance
    - .docker_europe_tags
  variables:
    DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
    INST_API_URL: "http://inst-api.service.${INSTANCE_DC}.consul"
    INST_UI_URL: "http://inst-ui.service.${INSTANCE_DC}.consul"
    INSTANCE_DC: mgcat-staging
    CONSUL_PATH: configs/checker

iron-prod2:
  extends:
    - .prod_instance
    - .docker_europe_tags
  variables:
    DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
    INST_API_URL: "http://inst-api.service.${INSTANCE_DC}.consul"
    INST_UI_URL: "http://inst-ui.service.${INSTANCE_DC}.consul"
    INSTANCE_DC: iron-prod2
    CONSUL_PATH: configs/checker

siam-prod2:
  extends:
    - .prod_instance
    - .docker_europe_tags
  variables:
    DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
    INST_API_URL: "http://inst-api.service.${INSTANCE_DC}.consul"
    INST_UI_URL: "http://inst-ui.service.${INSTANCE_DC}.consul"
    INSTANCE_DC: siam-prod2
    CONSUL_PATH: configs/checker


mattermost-prod:
  extends:
    - .prod_instance
    - .docker_europe_tags
  variables:
    DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
    INST_API_URL: "http://inst-api.service.${INSTANCE_DC}.consul"
    INST_UI_URL: "http://inst-ui.service.${INSTANCE_DC}.consul"
    INSTANCE_DC: mattermost-prod
    CONSUL_PATH: configs/checker
