prod instance:
  extends:
    - .prod_instance
    - .docker_europe_tags
  variables:
    DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
    INSTANCE_DC: ks-1
    CONSUL_PATH: configs/ks-1/checker/config

stage instance ks1:
  extends:
    - .stage_instance
    - .docker_europe_tags
  variables:
    DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
    INSTANCE_DC: ks-1
    CONSUL_PATH: configs/ks-1/checker/testconfig

mgcat-staging:
  extends:
    - .stage_instance
    - .docker_europe_tags
  variables:
    DEPLOY_REPO_URL: "git::ssh://git@jgit.me/sysadmin/checker//scripts/instantiator"
    INST_API_URL: "http://inst-api.service.${INSTANCE_DC}.consul"
    INST_UI_URL: "http://inst-ui.service.${INSTANCE_DC}.consul"
    INSTANCE_DC: mgcat-staging
    CONSUL_PATH: configs/checker
