.auto_version: &auto_version
  extends:
    - .create_version
    - .docker_europe_tags
  only:
    refs:
      - master

  except:
    refs:
      - tags

auto release patch:
  variables:
    ACTION: patch
  <<: *auto_version
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /##patch/

auto release feature:
  variables:
    ACTION: feature
  <<: *auto_version
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /##feature/

auto release major:
  variables:
    ACTION: major
  <<: *auto_version
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /##major/
