.build_inject_cmd: &build_inject_cmd |
  go build -ldflags \
  "-X my/checker/config.Version=${CI_COMMIT_REF_NAME}-fly -X my/checker/config.VersionSHA=${CI_COMMIT_SHORT_SHA}" \
  -o ${BINARY_NAME}

fly-deploy:
  stage: deploy
  image: golang:1.16
  before_script:
    - apt-get update -qq && apt-get install -y curl
    - curl -L https://fly.io/install.sh | sh
  script:
    - *build_inject_cmd
    - export FLY_API_TOKEN=$(vault read -field=token secret/fly.io/${FLY_ACCOUNT}/pass)
    - /root/.fly/bin/flyctl deploy
  extends:
    - .jgit_filter
    - .docker_europe_tags
  environment:
    name: fly-prod
  needs: []
