.go_lint: &go_lint
  stage: test
  script:
    - go get -u golang.org/x/lint/golint
    - whereis golint
    - golint ./...

.go_tests: &go_tests
  stage: test
  script:
    - go test -cover -v -coverprofile .testCoverage.txt ./...

go lint:
  <<: *go_lint
  extends:
    - .docker_europe_tags
    - .go_image

go tests:
  <<: *go_tests
  extends:
    - .docker_europe_tags
    - .go_image
