stages:
  - test
  - build
  - package
  - deploy
  - version

include:
  - local: .gitlab-ci.common.yml
  - local: .gitlab-ci.go-common.yml
  - local: .gitlab-ci.go-test.yml
  - local: .gitlab-ci.go-build.yml
  - local: .gitlab-ci.go-docker.yml
  - local: .gitlab-ci.inst-deploy.yml
  - project: "ci-library/common"
    file: ".gitlab-ci.version.yml"

retrive artifact:
  stage: package
  dependencies:
    - go linux
  extends:
    - .docker_europe_tag