defaults:
  duration: 1s
  alerts_channel: telegram
  maintenance_duration: 15m

db:
  protocol: postgres
  host: localhost:5438
  username: postgres
  password: postgres
  database: checker_test

alerts:
  telegram:
    type: telegram
    bot_token: 201865937:AAHBSXrIlEFSbVfUCvkkd3y4kbvJNgNIJuM
    critical_channel: 1390752
    noncritical_channel: 1390752

  slack:
    type: slack
    # Slack-specific fields

actors: []

projects:
  testProject:
    parameters:
      duration: 5s
    healthchecks:
      http:
        checks:
          Check google http:
            type: http
            url: https://google.com/
#      ping:
#        checks:
#          Check google ping:
#            parameters:
#              duration: 5s
#            type: ping
#            host: google.com
#      tcp:
#        checks:
#          Check google tcp:
#            parameters:
#              duration: 8s
#            type: tcp
#            host: google.com
#            port: 80