FROM golang:1.14

RUN go get -v -d ./... \
    && CGO_ENABLED=0 GOOS=linux go build -v -i -x -ldflags "-X my/checker/config.Version=${SOURCE_VERSION}" -o build/checker

FROM centos

COPY build/checker /bin/checker
COPY testconfigs/google.yaml /config.yaml

ENTRYPOINT ["/bin/checker"]
