[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
watchPatterns = ["/**"]

[deploy]
healthcheckPath = "/api/checks"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

