[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
watchPatterns = ["**"]

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
