defaults:
  duration: 10s
  alerts_channel: telegram
  maintenance_duration: 15m

db:
  protocol: mongodb
  host: cluster0.vjrpdjs.mongodb.net
  username: checker-dev
  database: checker_dev

alerts:
  telegram:
    type: telegram
    bot_token: 201865937:AAHBSXrIlEFSbVfUCvkkd3y4kbvJNgNIJuM
    critical_channel: 1390752
    noncritical_channel: 1390752

projects:

#  testProject4:
#    healthchecks:
#      checks_passive:
#        checks:
#          Passive#1:
#            type: passive
#            timeout: 120s

  testProject:
    parameters:
      duration: 14s
    healthchecks:
      checks_http:
        checks:
          Check google:
            type: http
            url: https://google.com/
            answer_present: true
#
#  testProject2:
#    parameters:
#      alerter: telegram
#    healthchecks:
#      checks_icmp:
#        checks:
#          Check google DNS:
#            type: icmp
#            host: 8.8.8.8
#            parameters:
#              duration: 30s
#          Check CloudFlare DNS:
#            type: icmp
#            host: 1.1.1.1
#            parameters:
#              duration: 10s
#
#  testProject3:
#    healthchecks:
#      checks_getfile:
#        checks:
#          Download hash:
#            type: getfile
#            url: https://download.mediaget.com/mediaget-installer-2/binaries/download.php?a=mediaget-lib
#            hash: cd32f76f2f15154ad63340bba2067744
#            parameters:
#              duration: 60s
#      checks_tcp:
#        checks:
#          Check SSH:
#            type: tcp
#            host: 163.172.108.18
#            timeout: 5s
#            port: 22468
