.go_build_inject:
  stage: build
  artifacts:
    expire_in: 30m
    paths:
      - build/${BINARY_NAME}
  script:
    - apk update && apk add git openssh gcc musl-dev
    - go build -ldflags \
      "-X my/checker/config.Version=${CI_COMMIT_REF_NAME} -X my/checker/config.VersionSHA=${CI_COMMIT_SHORT_SHA} -X my/checker/config.VersionBuild=${CI_JOB_ID}" \
      -o build/${BINARY_NAME}
  only:
    variables:
      - $INJECT_VERSION == "true"

go inject linux:
  variables:
    GOOS: "linux"
  extends:
    - .go_build_inject
    - .docker_europe_tags
    - .go_image

dev instance:
  script:
    - /bin/true

go tests:
  script:
    - /bin/true
