.build_inject_cmd: &build_inject_cmd |
  go build -ldflags \
  "-X my/checker/config.Version=${CI_COMMIT_REF_NAME}-fly -X my/checker/config.VersionSHA=${CI_COMMIT_SHORT_SHA}" \
  -o ${BINARY_NAME}

fly-deploy:
  stage: deploy
  image: harbor-ks.jgit.me/dockerhub_proxy/library/golang:1.17-alpine
  variables:
    APP: checker
    CHECKER_CONFIG: .helm/envs/fly/fly-ams.yaml
  before_script:
    - apk add --no-cache curl unzip gcc g++ musl-dev
    - wget -q https://releases.hashicorp.com/vault/1.8.5/vault_1.8.5_linux_amd64.zip
    - unzip vault_1.8.5_linux_amd64.zip
    - curl -L https://fly.io/install.sh | sh
    - export PATH="${PATH}:/root/.fly/bin/"
  script:
    - 'echo "access_token: $(./vault read -field=token secret/fly.io/${FLY_ACCOUNT}/pass)" > ~/.fly/config.yml'
    - *build_inject_cmd
    - flyctl apps create ${APP} || /bin/true
    - flyctl secrets set -a ${APP} --detach CHECKER_CONFIG=- < "${CHECKER_CONFIG}" || /bin/true
    - flyctl deploy -a ${APP}
  extends:
    - .jgit_filter
    - .docker_europe_tags
  environment:
    name: fly-prod
  needs:
    - go tests
