.deploy_instance:
  stage: deploy
  script:
    - echo "{}" | jq -f ${REQUEST_FILE} > params.json
    - jq -r '.' params.json
    - *run_cmd
    - *check_result
    - export INSTANCE_UUID=`jq -r '.payload.uuid' result.json`
    - export VERSION="$(cat images-report.json | jq -r .Images.stat.DockerImageName)"
    - echo "Status page - ${INST_UI_URL}/instance/${INSTANCE_UUID}"

prod instance:
  environment:
    name: ks1-prod
  extends:
    - .deploy_instance
    - .docker_europe_tags
  variables:
    CONSUL_PATH: configs/ks-1/checker/config
    REGISTRY_URL: "harbor-ks.jgit.me/releases"
  only:
    - tags

stage instance ks1:
  environment:
    name: stage
  extends:
    - .deploy_instance
    - .docker_europe_tags
  variables:
    CONSUL_PATH: configs/ks-1/checker/testconfig
    REGISTRY_URL: "harbor-ks.jgit.me/library"
  only:
    refs:
      - jgit
