.jgit_filter:
  only:
    refs:
      - jgit

.jgit_stage_instance:
  environment:
    name: stage
  extends:
    - .deploy_instance
    - .jgit_filter

.jgit_prod_instance:
  extends:
    - .deploy_instance
    - .tag_filter

stage instance:
  extends:
    - .jgit_stage_instance
    - .docker_europe_tags

.prod instance:
  extends:
    - .jgit_prod_instance
    - .docker_europe_tags

prod instance:
  environment:
    name: ks1-prod
  extends:
    - .prod_instance
    - .docker_europe_tags
  variables:
    CONSUL_PATH: configs/ks-1/checker/config
    REGISTRY_URL: "harbor-ks.jgit.me/releases"

stage instance ks1:
  extends:
    - .stage_instance
    - .docker_europe_tags
  variables:
    CONSUL_PATH: configs/ks-1/checker/testconfig
    REGISTRY_URL: "harbor-ks.jgit.me/library"
