.run_cmd: &run_cmd |
  if [[ CI_DEBUG_TRACE -ne "true" ]]; then CURL_OPTS="$CURL_OPTS -s"; fi
  curl $CURL_OPTS -X POST ${INST_API_URL}/instances \
  -H "Content-Type: application/json" \
  -d "@params.json" > result.json

.check_result: &check_result |
  if [[ `jq -r '.status' result.json` == "error" ]]; then jq -r '.' result.json; exit 2; else jq -r '.' result.json; fi

.deploy_instance:
  stage: deploy
  script:
    - echo "{}" | jq -f ${REQUEST_FILE} > params.json
    - jq -r '.' params.json
    - export VERSION="$(cat images-report.json | jq -r .Images.stat.DockerImageName)"
    - *run_cmd
    - *check_result
    - export INSTANCE_UUID=`jq -r '.payload.uuid' result.json`
    - echo "Status page - ${INST_UI_URL}/instance/${INSTANCE_UUID}"

prod instance:
  environment:
    name: ks1-prod
  extends:
    - .deploy_instance
    - .docker_europe_tags
  variables:
    CONSUL_PATH: configs/ks-1/checker/config
    REGISTRY_URL: "harbor-ks.jgit.me/releases"
  only:
    - tags

stage instance ks1:
  environment:
    name: stage
  extends:
    - .deploy_instance
    - .docker_europe_tags
  variables:
    CONSUL_PATH: configs/ks-1/checker/testconfig
    REGISTRY_URL: "harbor-ks.jgit.me/library"
  only:
    refs:
      - jgit
