.inst-run: &inst-run |
  curl -X POST \
    http://${INST_API}.service.${INST_DC}.consul/instances \
    -H 'Content-Type: application/json' \
    -d '{
      "name": "'${ENV}'",
      "project_name": "'${SERVICE}'",
      "auto_deploy": true,
      "datacenters": ["'${INST_DC}'"],
      "deploy_repository_url": "git::ssh://git@jgit.me/sysadmin/checker.git//scripts?ref=${CI_COMMIT_REF_NAME}",
      "overwrite": true,
      "params": {
          "version": "'${VERSION}'",
          "image": "'${VERSION}'",
          "env": "'${ENV}'",
          "backend_uri": "'${BACK_URI}'",
          "registry_host": "'${REGISTRY_HOST}'",
          "consul_path": "'${CONSUL_PATH}'",
          "registry_repo": "'${REGISTRY_REPO}'",
          "backend_uri": "",
          "deploy_by":"",
          "commit_sha":"",
          "gitlab_project":"",
          "commit_message":""
      }
  }'

.vars:
  variables:
    PROJECT: ks-1
    SERVICE: ${CI_PROJECT_NAME}
    INST_DC: ks-1
    INST_API: inst-api
    NOMAD_PROJECT: ks-1

.deploy to instantiator:
  stage: deploy
  before_script:
    ##### image name here                                     ++++
    - export VERSION=$(cat images-report.json | jq -r .Images.checker.DockerImageName)
  script:
    - set -x
    # - *generate_version
    - *inst-run
  extends:
    - .docker_europe_tags
    - .vars

prod instance:
  environment:
    name: ks1-prod
  extends:
    - .deploy to instantiator
    - .docker_europe_tags
  variables:
    CONSUL_PATH: configs/ks-1/checker/config
    ENV: checker-prod
  only:
    - tags

stage instance ks1:
  environment:
    name: stage
  extends:
    - .deploy to instantiator
    - .docker_europe_tags
  variables:
    CONSUL_PATH: configs/ks-1/checker/testconfig
    ENV: checker-jgit
  only:
    refs:
      - jgit
