prod instance:
  environment:
    name: ks1-prod
  extends:
    - .deploy_instance
    - .docker_europe_tags
  variables:
    CONSUL_PATH: configs/ks-1/checker/config
    REGISTRY_URL: "harbor-ks.jgit.me/releases"
  only:
    - tags

stage instance ks1:
  environment:
    name: stage
  extends:
    - .deploy_instance
    - .docker_europe_tags
  variables:
    CONSUL_PATH: configs/ks-1/checker/testconfig
    REGISTRY_URL: "harbor-ks.jgit.me/library"
  only:
    refs:
      - jgit
