version: '3.7'
services:
    postgres:
        image: postgres:17
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes:
          - ./db/postges:/var/lib/postgresql/data
