variables:
  CI_BUILD_ENV: scaleway
  CI_BUILD_REGISTRY: harbor-scw.jgit.me
  CI_BUILD_LIBRARY: checker/checker
  CI_DOCKER_PROXY: harbor-scw.jgit.me
  WERF_REPO_CONTAINER_REGISTRY: harbor

k8s siam:
  variables:
    WERF_ENV: siam
    DEPLOY_ENV: scaleway/binary-prod
  extends:
    - .werf_deploy_template
    - .docker_europe_tags
  only:
    - tags
  needs:
    - werf build
  environment:
    name: siam
    kubernetes:
      namespace: siam
    url: https://siamoption.com
    on_stop: k8s destroy siam

k8s destroy siam:
  variables:
    WERF_ENV: siam
    DEPLOY_ENV: scaleway/binary-prod
  extends:
    - .werf_destroy_template
    - .docker_europe_tags
  only:
    - tags
  when: manual
  environment:
    name: siam
    action: stop

k8s iron:
  variables:
    WERF_ENV: iron
    DEPLOY_ENV: scaleway/binary-prod
  extends:
    - .werf_deploy_template
    - .docker_europe_tags
  only:
    - tags
  needs:
    - werf build
  environment:
    name: iron
    kubernetes:
      namespace: iron
    url: https://irontrade.com
    on_stop: k8s destroy iron

k8s destroy iron:
  variables:
    WERF_ENV: iron
    DEPLOY_ENV: scaleway/binary-prod
  extends:
    - .werf_destroy_template
    - .docker_europe_tags
  only:
    - tags
  when: manual
  environment:
    name: iron
    action: stop
