{{- if and .Values.apiKey (not .Values.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "checker-edge.fullname" . }}
  labels:
    {{- include "checker-edge.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.apiKey | quote }}
{{- end }}
