CREATE TABLE IF NOT EXISTS check_definitions (
    uuid TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    project TEXT NOT NULL,
    group_name TEXT NOT NULL,
    type TEXT NOT NULL,
    description TEXT,
    enabled INTEGER DEFAULT 1,
    created_at DATETIME,
    updated_at DATETIME,
    last_run DATETIME,
    is_healthy INTEGER,
    last_message TEXT,
    last_alert_sent DATETIME,
    duration TEXT,
    actor_type TEXT,
    alert_type TEXT,
    alert_destination TEXT,
    config TEXT,
    actor_config TEXT
);
