---
defaults:
  http_port: '80'
  bots_enabled: true
  parameters:
    check_period: 900s
    report_period: 1800s
    min_health: 1
    allow_fails: 0
    noncrit_alert: telegram
    crit_alert: telegram
    command_channel: telegram
    mode: loud
    ssl_expiration_period: 720h
alerts:
  - name: telegram
    type: telegram
  << file "/vault/secrets/telegram.env" | indent 4 >>
projects:
  - name: binary-prod-siam
    healthchecks:
      - name: FXCloud redis-pre ticks
        type: redis_pubsub
        host: redis-pre-redis-ha-haproxy
        pubsub_config:
          - fxcloud_EUR/USD
      - name: Metatrader redis-pre ticks
        type: redis_pubsub
        host: redis-pre-redis-ha-haproxy
        pubsub_config:
          - ticks_EURUSD
      - name: Redis ticks
        type: redis_pubsub
        host: redis-redis-ha-haproxy
        pubsub_config:
          - quotes_EURUSD
      - name: Redis OTC ticks
        type: redis_pubsub
        host: redis-redis-ha-haproxy
        pubsub_config:
          - quotes_EURUSD_OTC
      - name: back
        parameters:
          check_period: 60s
        checks:
          - type: http
            host: http://app/monitor/status.php
            answer: .* OK$
            code:
              - 200
            timeout: 2s
            severity: critical
          - type: passive
            name: backend cron running
            timeout: 900s
            severity: critical
      - name: helpdesk
        checks:
          - type: http
            host: http://helpdesk/api/are-you-alive
            answer: ^Helpdesk.* OK$
            code:
              - 200
            timeout: 2s
      - name: web
        parameters:
          check_period: 60s
        checks:
          - type: http
            host: http://frontend
            answer: Trading platform
            code:
              - 200
            timeout: 2s
            severity: critical
      - name: ws
        parameters:
          check_period: 60s
        checks:
          - type: http
            host: http://ws/healthcheck
            code:
              - 200
            timeout: 2s
            severity: critical
      - name: cryptoindex
        checks:
          - type: http
            host: http://cryptoindex:8082/healthcheck
            code:
              - 200
            timeout: 2s
      - name: notify-trigger
        checks:
          - type: http
            host: http://notify-trigger/healthcheck
            answer: Triggers.* OK
            code:
              - 200
            timeout: 2s
      - name: notify-trigger-status
        checks:
          - type: http
            host: http://notify-trigger/healthcheck-full
            answer: Triggers.* OK
            code:
              - 200
            timeout: 2s
      - name: emailer
        checks:
          - type: http
            host: http://emailer/healthcheck
            answer: Emailer OK
            code:
              - 200
            timeout: 2s
      - name: statistics-aggregation
        checks:
          - type: http
            host: http://statistics-aggregation/healthcheck
            answer: StatisticsAggregationService OK
            code:
              - 200
            timeout: 2s
      - name: statistics-receiver
        checks:
          - type: http
            host: http://statistics-receiver/healthcheck
            answer: Stat_service OK
            code:
              - 200
            timeout: 2s
      - name: landings
        parameters:
          check_period: 60s
        checks:
          - type: http
            host: http://landings/api/are-you-alive
            answer: Landings OK
            code:
              - 200
            timeout: 2s
            severity: critical
      - name: private-api
        checks:
          - type: http
            host: http://private-api
            code:
              - 200
            timeout: 2s
      - name: exassets2bus-topfx
        parameters:
          check_period: 60s
        checks:
          - type: http
            host: http://exassets2bus-topfx:8081/health-check
            answer: '{"status":"ok"}'
            code:
              - 200
            timeout: 2s
            severity: critical

      - name: checker-fly.io active ping
        healthchecks:
          - name: Siam checker Running
            checks:
              - type: http
                host: https://checker.fly.dev/check/ping/dc07e03a-552c-5436-b15b-85495aa659bf
                code:
                  - 200
                timeout: 3s
