---
defaults:
  timer_step: 5s
  http_port: '80'
  bots_enabled: 'true'
  parameters:
    run_every: 900s
    min_health: 1
    allow_fails: 1
    noncrit_alert: tg_prod
    crit_alert: tg_prod
    command_channel: tg_prod
    mode: loud
    periodic_report_time: 1h
    ssl_expiration_period: 720h
    token_encryption_key: bi6oNuisa0ooz6Ael6Eewaatoophoo0p
alerts:
  - name: tg_prod
    type: telegram
    bot_token: 2132050809:AAE8LK-Yk_M58bcpgtWF9r6AzPBFSNJwyHE
    noncritical_channel: -730661309
    critical_channel: -730661309
#  - name: tg_main
#    type: telegram
#    bot_token: 988868513:AAHWL8ws-z2l2TLPbRb9jyyzJ-4HFbA71_k
#    noncritical_channel: 1390752
#    critical_channel: 1390752
projects:
  - name: Admitlead
    healthchecks:
      - name: Admitlead ks
        parameters:
          run_every: 60s
        checks:
          - type: http
            host: https://ks.admitlead.ru/main/check
            answer: AdmitLead OK
            code:
              - 200
            timeout: 3s
            severity: critical
  - name: BubblesMedia Critical
    healthchecks:
      - name: Bubbles ks
        parameters:
          run_every: 60s
        checks:
          - type: http
            host: http://s2.bubblesmedia.ru/main/check
            answer: Bubbles OK
            code:
              - 200
            timeout: 3s
            severity: critical
      - name: BubblesMedia content
        parameters:
          run_every: 60s
        checks:
          - type: http
            host: https://2.bubblesmedia.ru/invoke.php?id=42
            answer: (?is)<script>.*</script>
            code:
              - 200
            timeout: 3s
            severity: critical
      - name: BubblesMedia promo_code
        parameters:
          run_every: 60s
        checks:
          - type: http
            host: https://stat.bubblesmedia.ru/display/42/0
            answer: promo_code
            code:
              - 200
            timeout: 3s
            severity: critical

  - name: BubblesMedia Warning
    healthchecks:
      - name: BubblesMedia mg1
        checks:
          - type: http
            host: https://mg.bubblesmedia.ru/for_check.php
            answer: mg1 OK
            code:
              - 200
            timeout: 3s

  - name: Mediaget Critical
    healthchecks:
      - name: 'Mediaget site'
        parameters:
          run_every: 60s
        checks:
          - type: http
            host: https://mediaget.com/ping
            answer: pong
            code:
              - 200
            timeout: 3s
            severity: critical
      - name: 'Mediaget Client'
        parameters:
          run_every: 60s
        checks:
          - type: http
            host: https://mediaget.com/client/check.php
            answer: ProjectM2Client OK
            code:
              - 200
            timeout: 3s
            severity: critical
      - name: 'Mediaget LD'
        parameters:
          run_every: 60s
        checks:
          - type: http
            host: https://mediaget.com/ld/check.php
            answer: ProjectM2Ld OK
            code:
              - 200
            timeout: 3s
            severity: critical
      - name: 'Mediaget Catalogue API'
        parameters:
          run_every: 60s
        checks:
          - type: http
            host: https://mediaget.com/api/healthcheck
            answer: API OK
            code:
              - 200
            timeout: 3s
            severity: critical

  - name: Mediaget Warning
    healthchecks:
      - name: 'Mediaget DHT API'
        checks:
          - type: http
            host: https://mediaget.com/dht/healthcheck
            answer: API OK
            code:
              - 200
            timeout: 3s
      - name: 'Mediaget Similarity API'
        checks:
          - type: http
            host: https://mediaget.com/similarity/healthcheck
            answer: searcher-similarity OK
            code:
              - 200
            timeout: 3s
      - name: 'Mediaget Searcher API'
        checks:
          - type: http
            host: https://mediaget.com/search/healthcheck
            answer: searcher-search OK
            code:
              - 200
            timeout: 3s
      - name: 'Mediaget Update HashServer'
        checks:
          - type: http
            host: https://hash-server.com/update.php?version=2.01.3780
            answer: 2a2672ad7f33ed65172ddaebef481de6f98e34c6
            code:
              - 200
            timeout: 3s
      - name: 'MG2Parser content error'
        checks:
          - type: http
            host: https://mediaget.com/parser/update.ini
            answer: search_server
            code:
              - 200
            timeout: 3s
      - name: 'MG2Client content error'
        checks:
          - type: http
            host: https://mediaget.com/client/client.php
            answer: <Status>500</Status>
            code:
              - 200
            timeout: 3s
      - name: 'MG2Ld content error'
        checks:
          - type: http
            host: https://mediaget.com/ld/get_data.php?id=1
            answer: <parameters>
            code:
              - 200
            timeout: 3s
      - name: 'MG2ApiDHT content error'
        checks:
          - type: http
            name: MG2ApiDHTSearch
            host: https://mediaget.com/dht/v1/torrents/search?q=avatar&page=1&page_size=10
            answer: avatar
            code:
              - 200
            timeout: 3s
          - type: http
            name: MG2ApiDHTMoviesID
            host: https://mediaget.com/dht/v1/torrents/movies/384436?lang=en&page=1&page_size=10
            answer: Avatar
            code:
              - 200
            timeout: 3s

  - name: Mediaget OLD
    healthchecks:
      - name: 'old Mediaget torr'
        checks:
          - type: http
            host: https://torr.mediaget.com/for_check.php
            answer: torr1 OK
            code:
              - 200
            timeout: 10s
      - name: 'old Mediaget Client'
        checks:
          - type: http
            host: https://client.mediaget.com/check_statistic_db.php
            answer: ProjectMClient OK
            code:
              - 200
            timeout: 3s

  - name: Faceless
    healthchecks:
      - name: 'Faceless site'
        checks:
          - type: http
            host: https://faceless.me/monitor.php
            answer: Faceless OK
            code:
              - 200
            timeout: 3s

      - name: 'Faceless Backend API'
        checks:
          - type: http
            host: https://api.faceless.me/health-check
            answer: code.:200
            code:
              - 200
            timeout: 3s

  - name: Orbitum
    healthchecks:
      - name: Orbitum Stat
        checks:
          - type: http
            host: https://stat.orbitum.com/check_orbitum_stat.php
            answer: ProjectOStatistic OK
            code:
              - 200
            timeout: 3s
      - name: Orbitum Site
        checks:
          - type: http
            host: https://orbitum.com/check_site_db.php
            answer: ProjectO OK
            code:
              - 200
            timeout: 3s
      - name: Orbitum Services
        checks:
          - type: http
            name: MusicOrbitum
            host: http://music.orbitum.com/monitor.php
            answer: MusicOrbitum OK
            code:
              - 200
            timeout: 3s
          - type: http
            name: gamebackend
            host: http://gamesbackend.com/monitor.php
            answer: gamebackend OK
            code:
              - 200
            timeout: 3s
          - type: http
            name: SDSearchAPI
            host: http://search-sd.orbitum.com/check.php
            answer: SDSearchAPI OK
            code:
              - 200
            timeout: 3s
          - type: http
            name: SDPublicAPI
            host: http://sd.orbitum.com/check.php
            answer: SDPublicAPI OK
            code:
              - 200
            timeout: 3s
          - type: http
            name: OrbitumSD
            host: http://ext.orbitum.com/myspeed_tips/api/checksite.php
            answer: OrbitumSD OK
            code:
              - 200
            timeout: 3s
          - type: http
            name: ThemesApi
            host: https://beta-themes.orbitum.com/check.php
            answer: ThemesApi OK
            code:
              - 200
            timeout: 3s
          - type: http
            name: ThemesCDN
            host: https://bcdn-themes.orbitum.com/check.php
            answer: ThemesCDN OK
            code:
              - 200
            timeout: 3s
          - type: http
            name: AdBlock blacklist answer
            host: https://extupdate.orbitum.com/adblock/blacklist.txt
            code:
              - 200
            timeout: 3s
          - type: http
            name: AdBlock search answer
            host: https://extupdate.orbitum.com/adblock/search.txt
            code:
              - 200
            timeout: 3s
          - type: http
            name: ExtensionSearch content
            host: http://extension-search.online/suggest/get?part=%D0%B2%D0%BA
            answer: вконтакте
            code:
              - 200
            timeout: 3s
          - type: http
            name: ExtensionSearchRedirect content
            host: http://extension-search.online/?q=vk
            answer: Яндекс
            code:
              - 200
            timeout: 3s
          - type: http
            name: ProjectOBbls1 answer
            host: http://admin:khgbkjkhjfhvb@bbls1.orbitum.com/index.php
            code:
              - 200
            timeout: 3s
          - type: http
            name: ThemesCDN
            host: https://bcdn-themes.orbitum.com/check.php
            answer: ThemesCDN OK
            code:
              - 200
            timeout: 3s

  - name: IronTrade Staging
    healthchecks:
      - name: IronStagingFrontend
        checks:
          - type: http
            host: https://web.iron-staging.irontrade.com/
            answer: <title>Trading platform</title>
            code:
              - 200
            timeout: 3s
      - name: IronStagingBackend
        checks:
          - type: http
            host: https://web.iron-staging.irontrade.com/app/monitor/status.php?mode=test
            answer: IronTrade OK
            code:
              - 200
            timeout: 3s
      - name: IronStagingServices
        checks:
          - type: http
            name: Helpdesk
            host: https://web.iron-staging.irontrade.com/hc/api/are-you-alive
            answer: HelpdeskIrontrade OK
            code:
              - 200
            timeout: 3s
          - type: http
            name: StatReceiver
            host: https://web.iron-staging.irontrade.com/sr/healthcheck
            answer: Stat_service OK
            code:
              - 200
            timeout: 3s

  - name: GetDietApp
    healthchecks:
      - name: API
        checks:
          - type: http
            name: API EN
            host: https://api-en.getdietapp.com/api/healthcheck
            answer: GetDietapp-en-prod OK
            code:
              - 200
            timeout: 3s
          - type: http
            name: API RU
            host: https://api.getdietapp.com/api/healthcheck
            answer: GetDietapp-prod OK
            code:
              - 200
            timeout: 3s

  - name: MyMentalMentor
    healthchecks:
      - name: MyMentorAPI
        checks:
          - type: http
            host: https://api.mymentalmentor.net/health-check
            answer: code.:200
            code:
              - 200
            timeout: 3s

  - name: Domec
    healthchecks:
      - name: DomecWebsite
        checks:
          - type: http
            host: https://domec.ru/
            answer: js.jquery\.pngFix\.js
            code:
              - 200
            timeout: 3s

  - name: AdsKiller
    healthchecks:
      - name: AdsKiller
        checks:
          - type: http
            name: adBlockStats
            host: https://stat.adskiller.me
            answer: <title>adBlockStats ADMIN</title>
            code:
              - 200
            timeout: 3s
          - type: http
            name: adskiller.me content
            host: https://adskiller.me/
            answer: <title>Ads Killer</title>
            code:
              - 200
            timeout: 3s
          - type: http
            name: install.adskiller.me/conf.php content error
            host: http://install.adskiller.me/conf.php?id=jjckigopagkhaikodedjnmbccfpnmiea
            answer: active_permissions
            code:
              - 200
            timeout: 3s
          - type: http
            name: AdsKiller api/settings content error
            host: https://stat.adskiller.me/external/api/settings
            answer: time_interval
            code:
              - 200
            timeout: 3s
          - type: http
            name: AdsKiller api/list content error
            host: https://stat.adskiller.me/external/api/list
            answer: update.adskiller.me
            code:
              - 200
            timeout: 3s

  - name: CrossCheck ASIA
    healthchecks:
      - name: Checker Running
        checks:
          - type: passive
            timeout: 960s
            severity: critical
