name: Go

on:
  push:
    branches-ignore:
      - "master"
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BINARY_NAME: "checker"

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get Branch
        run: |
          branch=$( echo ${{ github.ref }} | sed 's/^.*\/.*\///g')
          echo ::set-env name=VERSION::$branch

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v -i -ldflags "-X my/checker/config.Version=${{ env.VERSION }} -X my/checker/config.VersionSHA=${GITHUB_SHA} -X my/checker/config.VersionBuild=${GITHUB_RUN_ID}" -o ${{ env.BINARY_NAME }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BINARY_NAME }}
          path: ${{ env.BINARY_NAME }}

#      - name: Upload a Build Artifact
#        uses: superfly/flyctl-actions@1.1
#        with:
#          args: "deploy"
